// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoWItems.API.DbContexts;

#nullable disable

namespace WoWItems.API.Migrations
{
    [DbContext(typeof(WoWItemsContext))]
    [Migration("20221031023200_UpdateAPI2")]
    partial class UpdateAPI2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WoWItems.API.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("Durability")
                        .HasColumnType("int");

                    b.Property<string>("EquipEffect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stamina")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UseEffect")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Armor = 0,
                            Durability = 145,
                            EquipEffect = "Deals 5 fire dmg to anyone who strikes you with mele attack",
                            Name = "Sulfuras, Hand of Ragnaros",
                            Stamina = 12,
                            Type = 1,
                            UseEffect = ""
                        },
                        new
                        {
                            Id = 2,
                            Armor = 679,
                            Durability = 120,
                            EquipEffect = "",
                            Name = "Ruined Crest of Lorderon",
                            Stamina = 81,
                            Type = 0,
                            UseEffect = ""
                        });
                });

            modelBuilder.Entity("WoWItems.API.Entities.PrimaryStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryStatType")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("PrimaryStat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 1,
                            PrimaryStatType = 1,
                            Value = 12
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 2,
                            PrimaryStatType = 0,
                            Value = 133
                        });
                });

            modelBuilder.Entity("WoWItems.API.Entities.SecondaryStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryStatType")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("SecondaryStat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 2,
                            SecondaryStatType = 1,
                            Value = 21
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 2,
                            SecondaryStatType = 2,
                            Value = 52
                        });
                });

            modelBuilder.Entity("WoWItems.API.Entities.PrimaryStat", b =>
                {
                    b.HasOne("WoWItems.API.Entities.Item", null)
                        .WithMany("PrimaryStat")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WoWItems.API.Entities.SecondaryStat", b =>
                {
                    b.HasOne("WoWItems.API.Entities.Item", null)
                        .WithMany("SecondaryStats")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WoWItems.API.Entities.Item", b =>
                {
                    b.Navigation("PrimaryStat");

                    b.Navigation("SecondaryStats");
                });
#pragma warning restore 612, 618
        }
    }
}
