// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoWItems.API.DbContexts;

#nullable disable

namespace WoWItems.API.Migrations
{
    [DbContext(typeof(WoWItemsContext))]
    [Migration("20221020134935_WoWItemsDBInitialMigration")]
    partial class WoWItemsDBInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("WoWItems.API.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Armor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Durabity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipEffect")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UseEffect")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WoWItems.API.Entities.PrimaryStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryStatType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("PrimaryStat");
                });

            modelBuilder.Entity("WoWItems.API.Entities.SecondaryStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondaryStatType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("SecondaryStat");
                });

            modelBuilder.Entity("WoWItems.API.Entities.PrimaryStat", b =>
                {
                    b.HasOne("WoWItems.API.Entities.Item", "Item")
                        .WithOne("PrimaryStat")
                        .HasForeignKey("WoWItems.API.Entities.PrimaryStat", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WoWItems.API.Entities.SecondaryStat", b =>
                {
                    b.HasOne("WoWItems.API.Entities.Item", "Item")
                        .WithMany("SecondaryStats")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WoWItems.API.Entities.Item", b =>
                {
                    b.Navigation("PrimaryStat")
                        .IsRequired();

                    b.Navigation("SecondaryStats");
                });
#pragma warning restore 612, 618
        }
    }
}
